name: Practice
authors: [Kezuk, tetelie]
version: 1.0
description: Practice plugin developed for Bawz.
main: kezuk.practice.Practice
commands:
  arena:
  duel:
    aliases: [d]
  accept:
    aliases: [a]
  deny:
  party:
    aliases: [p, group, groupe]
  spectate:
    aliases: [spec, s]
  join:
    aliases: [j]
  inventory:
    aliases: [inv]
  rank:
  tag:
  build:
